services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate:/etc/nginx/certificate
      - wordpress_data:/usr/share/nginx/html
    depends_on:
      - wordpress
    networks:
      - frontend

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:
