services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    environment:
      - DOMAIN_NAME=trusanov.42.fr
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate:/etc/nginx/certificate
      - wordpress_data:/usr/share/nginx/html
    depends_on:
      - wordpress
    networks:
      - frontend

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:
