services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./certificate:/etc/nginx/certificate
      - wordpress_data:/usr/share/nginx/html
    secrets:
      - nginx-ssl-certificate
      - nginx-ssl-key
    depends_on:
      - wordpress
    networks:
      - frontend

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - mariadb-password
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - mariadb-root
      - mariadb-password
    networks:
      - backend

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:

secrets:
  mariadb-root:
    file: ../secrets/mariadb-root.txt
  mariadb-password:
    file: ../secrets/mariadb-password.txt
  nginx-ssl-certificate:
    file: ../secrets/nginx-ssl.crt
  nginx-ssl-key:
    file: ../secrets/nginx-ssl.key
